### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by dima117** [dima117/thinking-home#2]
Ввел http://localhost:41831 и получил ошибку: handler for url '/favicon.ico' is not found.

at ThinkingHome.Plugins.Listener.CommonController.Index() in c:\Projects\Thinking-Home\ThinkingHome.Plugins.Listener\CommonApiController.cs:line 53
at lambda_method(Closure , Object , Object[] )
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by dima117** [comment]
Добавлен favicon
